export enum endpoint {
  GET_MOVIE_GENRE = "/3/genre/movie/list",
  GET_TRENDING_MOVIES = "/3/trending/movie/",
  GET_UPCOMING_MOVIES = "/3/movie/upcoming?page=",
  GET_MOVIE_DETAILS = "/3/movie/",
  GET_MOVIE_IMAGES = "/3/movie/",
  GET_CAST_OF_MOVIES = "/3/movie/",
  GET_YOUTUBE_KEY = "/3/movie/",
  GET_MOVIE_CERTIFICATIONS = "/3/certification/movie/list",
  GET_MOVIE_BY_SEARCH_QUERY = "/3/search/movie?",
  GET_AVAILABLE_REGIONS = "/3/watch/providers/regions",
  GET_CAST_INFO = "/3/person/",
  GET_MOVIE_REVIEW = "/3/movie/",
  GET_COMBINED_MOVIE_CREDITS_OF_CAST = "/3/person/",
  GET_MOVIE_BY_MULTI_SEARCH = "/3/search/multi?",
  GET_TV_SERIES_DETAILS = "/3/tv/",
  GET_TV_SERIES_IMAGES = "/3/tv/",
  GET_CAST_OF_TV_SERIES = "/3/tv/",
  GET_TV_SERIES_REVIEWS = "/3/tv/",
  GET_TV_SERIES_YOUTUBE_KEY = "/3/tv/",
}
